on: [push, pull_request]

name: Continuous integration

jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - run: apt update && apt install -y alsa
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - run: cargo check
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo build
      - run: cargo test